avniproject/avni-webapp

src/orgManager/OrgManager.js
src/orgManager/catchment.js

Changes consist- displaying catchment list. And to add a  new catchment button & its form.

catchment display changes

---

src/formDesigner/components/Concepts.js

1. Search a concept.
2. Void a concept.
3. Listing a concept.

Replace remote data with single call API.

---

src/dataEntryApp/components/CodedFormElement.js
src/dataEntryApp/components/DateOfBirth.js
src/dataEntryApp/components/LocationAutosuggest.js
src/dataEntryApp/components/TextFormElement.js
src/dataEntryApp/sagas/subjectSaga.js
src/dataEntryApp/views/registration/SubjectRegister.js

introduce autosuggest address field in subject registration
few UI changes

[DataEntryApp] [RegistrationScreen] UI changes

---

src/adminApp/EncounterTypes.js
src/adminApp/SubjectTypes.js
src/adminApp/addressLevelType.js
src/adminApp/catchment.js
src/adminApp/locations.js
src/adminApp/programs.js
src/adminApp/user.js
src/formDesigner/views/CreateEditConcept.js
src/formDesigner/views/FormDetails.js

#1093 | Add audit data to all entities

---

src/formDesigner/components/FormSettings.js
src/formDesigner/views/FormDetails.js

made ui changes and align button to right side.

#178 | Redesign tabs on form details page

---

src/adminApp/CustomFilters.js
src/adminApp/OrgManager.js
src/adminApp/OrgManagerAppDesigner.js
src/adminApp/OrganisationConfig.js
src/adminApp/WorklistUpdationRule.js
src/adminApp/components/CreateEditLanguages.js
src/adminApp/customRoutes.js
src/adminApp/react-admin-config/dataProvider.js

Created seperate entities 
- In Admin section :
Language entity
- In App Designer section : 
My dashboard filters
Search Filters
Worklist  Updation Rule

#225 | Seperate out language and filters in ui designer

---

src/formDesigner/common/constants.js
src/formDesigner/components/FormSettings.js
src/formDesigner/components/NewFormModal.js

Individual encounter cancellation

---

src/dataEntryApp/api/browserStore.js
src/dataEntryApp/components/Form.js
src/dataEntryApp/components/FormElementGroup.js
src/dataEntryApp/reducers/programEnrolReducer.js
src/dataEntryApp/sagas/programSaga.js
src/dataEntryApp/sagas/subjectSaga.js
src/dataEntryApp/views/registration/FormWizard.js
src/dataEntryApp/views/subjectDashBoard/components/CommonModal.js
src/dataEntryApp/views/subjectDashBoard/components/ProfileDetails.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEnrol.js

New program enrolment

---

src/common/adapters.js
src/common/constants.js
src/common/subjectModelMapper.js
src/dataEntryApp/api/browserStore.js
src/dataEntryApp/components/LocationAutosuggest.js
src/dataEntryApp/components/RadioButtonsGroup.js
src/dataEntryApp/reducers/registrationReducer.js
src/dataEntryApp/sagas/subjectDashboardSaga.js
src/dataEntryApp/sagas/subjectSaga.js
src/dataEntryApp/views/registration/FormWizard.js
src/dataEntryApp/views/registration/SubjectRegister.js

Subject registration gaps- Subject Address#198 user story and [Bug] Address not shown correctly on subject details next screen after address filled up#334 are completed please review and merge the changes.

Subject registration addressgaps

---

src/common/subjectModelMapper.js
src/dataEntryApp/views/subjectDashBoard/components/ViewVisit.js

View Visit refresh fix

---

src/dataEntryApp/views/registration/SubjectRegister.js

No Detail removed from registration page

---

src/dataEntryApp/sagas/programSaga.js
src/dataEntryApp/sagas/subjectDashboardSaga.js
src/dataEntryApp/views/subjectDashBoard/components/ProfileDetails.js

description: fixed issue for Getting to see previously opened profile for a brief time.

defect: #415 fix

---

src/dataEntryApp/components/LocationAutosuggest.js
src/dataEntryApp/views/registration/SubjectRegister.js

Code changes for bug#351

---

src/common/subjectModelMapper.js
src/dataEntryApp/DataEntry.js
src/dataEntryApp/components/Breadcrumbs.js
src/dataEntryApp/reducers/dataEntryReducer.js
src/dataEntryApp/reducers/encounterReducer.js
src/dataEntryApp/sagas/encounterSaga.js
src/dataEntryApp/sagas/encounterSelector.js
src/dataEntryApp/sagas/index.js
src/dataEntryApp/views/subjectDashBoard/SubjectDashboard.js
src/dataEntryApp/views/subjectDashBoard/components/NewGeneralVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewProgramVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewVisitMenuView.js
src/dataEntryApp/views/subjectDashBoard/components/SubjectDashboardTabs.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardGeneralTab.js
translations/en.json

Created WIP Pull request for "Ability to choose an Encounter#128"
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/128

WIP PR for #128 - added ability to choose possible encounters initial changes

---

src/dataEntryApp/components/CodedFormElement.js
src/dataEntryApp/components/DateFormElement.js
src/dataEntryApp/components/DateOfBirth.js
src/dataEntryApp/components/FormElement.js
src/dataEntryApp/components/NumericFormElement.js
src/dataEntryApp/components/TextFormElement.js
src/dataEntryApp/components/TimeFormElement.js
src/dataEntryApp/views/registration/SubjectRegister.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEnrol.js

Code Changes are done for Bug#387

Code Changes for the Bug#387

---

src/dataEntryApp/DataEntry.js
src/dataEntryApp/api/index.js
src/dataEntryApp/components/Breadcrumbs.js
src/dataEntryApp/reducers/encounterReducer.js
src/dataEntryApp/sagas/encounterSaga.js
src/dataEntryApp/sagas/encounterSelector.js
src/dataEntryApp/sagas/programEncounterSaga.js
src/dataEntryApp/services/EncounterService.js
src/dataEntryApp/services/FormElementService.js
src/dataEntryApp/views/subjectDashBoard/SubjectDashboard.js
src/dataEntryApp/views/subjectDashBoard/components/CompletedEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/Encounter.js
src/dataEntryApp/views/subjectDashBoard/components/EncounterForm.js
src/dataEntryApp/views/subjectDashBoard/components/NewGeneralVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewProgramVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewVisitMenuView.js
src/dataEntryApp/views/subjectDashBoard/components/PlannedEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/SubjectDashboardTabs.js
src/dataEntryApp/views/subjectDashBoard/components/Visit.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardGeneralTab.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardProgramDetails.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardProgramTab.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardProgramView.js
translations/en.json
translations/gu_IN.json
translations/hi_IN.json
translations/mr_IN.json

Created WIP Pull request for "New Encounter#129"
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/129

WIP PR for #129 -  intial changes for new encounter

---

src/dataEntryApp/DataEntry.js
src/dataEntryApp/reducers/encounterReducer.js
src/dataEntryApp/sagas/encounterSaga.js
src/dataEntryApp/views/subjectDashBoard/components/CompletedEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/Encounter.js
src/dataEntryApp/views/subjectDashBoard/components/PlannedEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardGeneralTab.js

Created WIP Pull request for "Edit Encounter#130"
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/130

WIP PR for #130- Edit encounter

---

src/dataEntryApp/reducers/encounterReducer.js
src/dataEntryApp/reducers/programEncounterReducer.js
src/dataEntryApp/sagas/completedVisitSaga.js
src/dataEntryApp/sagas/encounterSaga.js
src/dataEntryApp/sagas/encounterSelector.js
src/dataEntryApp/sagas/programEncounterSaga.js
src/dataEntryApp/sagas/programEncounterSelector.js
src/dataEntryApp/views/subjectDashBoard/NewCompletedVisitsTable.js
src/dataEntryApp/views/subjectDashBoard/components/CancelEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/CancelProgramEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/CancelProgramEncounterForm.js
src/dataEntryApp/views/subjectDashBoard/components/CompletedVisits.js
src/dataEntryApp/views/subjectDashBoard/components/Encounter.js
src/dataEntryApp/views/subjectDashBoard/components/NewGeneralVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewProgramVisit.js
src/dataEntryApp/views/subjectDashBoard/components/NewVisitMenuView.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/Visit.js
src/dataEntryApp/views/subjectDashBoard/components/subjectDashboardGeneralTab.js

Improvements and changes for the new program encounter.

WIP PR for - New program encounter

---

src/dataEntryApp/components/DateFormElement.js
src/dataEntryApp/components/DateOfBirth.js
src/dataEntryApp/components/TimeFormElement.js
src/dataEntryApp/views/registration/SubjectRegister.js
src/dataEntryApp/views/subjectDashBoard/components/AddRelative.js
src/dataEntryApp/views/subjectDashBoard/components/FindRelative.js
src/dataEntryApp/views/subjectDashBoard/components/FindRelativeTable.js
src/dataEntryApp/views/subjectDashBoard/components/GridCommonList.js
src/dataEntryApp/views/subjectDashBoard/components/ProfileDetails.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEnrol.js
src/dataEntryApp/views/subjectDashBoard/components/RemoveRelative.js
src/dataEntryApp/views/subjectDashBoard/components/SubjectDashboardProfileTab.js

Code Changes are done for the Add relative and remove the related issue

Addrelative#150

---

src/dataEntryApp/components/TimeFormElement.js
src/dataEntryApp/services/ProgramEncounterService.js
src/dataEntryApp/services/ProgramEnrolmentService.js
src/dataEntryApp/views/subjectDashBoard/components/CancelProgramEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEncounter.js
src/dataEntryApp/views/subjectDashBoard/components/ProgramEnrol.js

-- Modified time in "HH:mm" format
-- Added enrolment and program encouter date validations

Date bug fix

---

.circleci/config.yml
Dockerfile

This PR introduces a Dockerfile to the project, providing instructions for building a Docker image of the Avni Webapp. Additionally, the workflow configuration has been updated to facilitate the Dockerization process.

Add Dockerfile and CI job for creating Docker image

---

src/adminApp/addressLevelType.js
src/adminApp/catchment.js
src/adminApp/locations.js

Fixes #974
1. For App Designer it already resolved.
2. For Users unable to find uuid.
1. Find related component.
2. Added Textfield component for uuid.
1. go to show page and verify uuid
2. check with sql query from backend.

Added Textfield for UUID

---

src/adminApp/OrgManager.js
src/adminApp/OrgManagerContext.js
src/adminApp/user.js

Fixes #889 
1. **OrgManager** Component is re rendering when we are typing in the input field. I find that in props location is causing the re render.
2. It create memory leak issue.
1. I added **shouldComponentUpdate** lifecycle method in **OrgManager** component.
1. checked with putting log in render and other lifecycle method.

#889 | Re rendering of OrgManger is fixed.

---

src/dataEntryApp/components/CustomizedSnackbar.js

 #1199 | Snackbar color corrected(changed to red) when profile picture URL incorrect

---

src/tutorials/Resources.js

Fix for issue #1233 Updated Url of Self service help articles to  https://avni.readme.io/docs/implementers-concept-guide-introduction

fix: update Self service help article link

---

src/adminApp/Organisation.js

- Fixed Typo in Username Suffix.
- Trimed and Normalized Whitespaces in Input Fields 
Fixes #1441

fix: Fix Typo in Username Suffix Trim and Normalize Whitespaces

---

src/adminApp/OrganisationGroup.js

Db to DB User and trim and normalization of input values fixed 18/3/25
